# Generated by Django 5.0.6 on 2024-10-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('All Levels', 'All Levels')], max_length=20)),
                ('workout_type', models.CharField(choices=[('Strength Training', 'Strength Training'), ('HIIT', 'HIIT'), ('Yoga', 'Yoga'), ('Dance', 'Dance'), ('Cardio', 'Cardio'), ('Core Training', 'Core Training'), ('Circuit Training', 'Circuit Training'), ('Plyometrics', 'Plyometrics')], max_length=20)),
                ('equipment_needed', models.CharField(blank=True, max_length=100, null=True)),
                ('sets', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
                ('rest_time', models.PositiveIntegerField(help_text='Rest time in seconds')),
                ('exercises', models.TextField(help_text='Comma-separated list of exercises')),
                ('target_muscle_groups', models.CharField(max_length=100)),
                ('progression', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_ratings', models.FloatField(help_text='Rating out of 5')),
                ('last_updated_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Workout Routine',
                'verbose_name_plural': 'Workout Routines',
            },
        ),
    ]
