# Generated by Django 5.1 on 2024-10-30 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0002_workoutroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('calories_per_hour', models.IntegerField()),
                ('image_url', models.URLField()),
                ('image_url_secondary', models.URLField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LOSE_WEIGHT', 'Lose Weight'), ('MAINTAIN_WEIGHT', 'Maintain Weight'), ('GAIN_WEIGHT', 'Gain Weight'), ('GAIN_MUSCLE', 'Gain Muscle'), ('MODIFY_DIET', 'Modify My Diet')], max_length=30, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='food',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fitness_goal',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='manganese',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='selenium',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='vitamin_b11',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='vitamin_b12',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='vitamin_b3',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='vitamin_b5',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='vitamin_b6',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='zinc',
        ),
        migrations.AddField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('very', 'Very Active'), ('extra', 'Extra Active')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='daily_calorie_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Caloric Intake', 'Caloric Intake')], max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitedSync.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FitedSync.workoutroutine')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='fitness_goals',
            field=models.ManyToManyField(blank=True, to='FitedSync.fitnessgoal'),
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=50)),
                ('quantity', models.FloatField(help_text='Quantity in grams or serving size')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitedSync.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('total_calories_consumed', models.FloatField(default=0)),
                ('total_calories_burned', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitedSync.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitedSync.workoutroutine')),
            ],
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
