# Generated by Django 5.1 on 2024-10-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0003_exercise_fitnessgoal_rename_food_fooditem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='copper',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='dietary_fiber',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='magnesium',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='last_updated_date',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='progression',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='rest_time',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='user_ratings',
        ),
    ]
