# Generated by Django 5.1 on 2024-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0004_remove_fooditem_copper_remove_fooditem_dietary_fiber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='name',
            new_name='food',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='calories_per_hour',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_gp_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
