# Generated by Django 5.1 on 2024-10-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0005_rename_name_exercise_title_rename_name_fooditem_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutroutine',
            name='repetitions',
            field=models.CharField(max_length=50),
        ),
    ]
