# Generated by Django 5.1 on 2024-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='name',
            field=models.CharField(choices=[('LOSE_WEIGHT', 'Lose weight'), ('MAINTAIN_WEIGHT', 'Maintain weight'), ('GAIN_WEIGHT', 'Gain weight'), ('GAIN_MUSCLE', 'Gain muscle'), ('MODIFY_DIET', 'Modify my diet')], max_length=30, unique=True),
        ),
    ]
