# Generated by Django 5.1 on 2024-11-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0008_alter_fitnessgoal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(choices=[('lightly_active', 'Lightly Active'), ('not_very_active', 'Not Very Active'), ('very', 'Very Active'), ('active', 'Active')], default='active', max_length=20),
        ),
    ]
