# Generated by Django 5.1 on 2024-11-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0011_alter_customuser_activity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Not Very Active'), ('very_active', 'Very Active'), ('extra_active', 'Extra Active')], default='moderately_active', max_length=20),
        ),
    ]
