# Generated by Django 5.1 on 2024-11-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0012_alter_customuser_activity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_routines', to='FitedSync.exercise'),
        ),
    ]
