# Generated by Django 5.1 on 2024-11-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0013_remove_exercise_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutroutine',
            name='exercise',
            field=models.ManyToManyField(related_name='workout_routines', to='FitedSync.exercise'),
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='exercises',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
