# Generated by Django 5.1 on 2024-11-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0014_workoutroutine_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutroutine',
            name='exercises',
            field=models.TextField(max_length=100),
        ),
    ]
