# Generated by Django 5.1 on 2024-11-10 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0015_alter_workoutroutine_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='workout_routine',
        ),
        migrations.CreateModel(
            name='CustWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sets', models.PositiveIntegerField()),
                ('repetitions', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('All Levels', 'All Levels')], max_length=20)),
                ('exercise', models.ManyToManyField(to='FitedSync.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='CustWorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cust_routine_name', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('routine_name', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
