# Generated by Django 5.1 on 2024-11-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0016_remove_exerciselog_workout_routine_custworkout_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustWorkoutLog',
        ),
    ]
