# Generated by Django 5.1 on 2024-11-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0018_custworkout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custworkout',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='custworkout',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='custworkout',
            name='sets',
        ),
        migrations.CreateModel(
            name='CustWorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitedSync.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='FitedSync.custworkout')),
            ],
            options={
                'unique_together': {('workout', 'exercise')},
            },
        ),
    ]
