# Generated by Django 5.1 on 2024-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0020_alter_meal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meallog',
            name='protein',
            field=models.FloatField(null=True),
        ),
    ]
