# Generated by Django 5.1 on 2024-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0021_meallog_calories_meallog_carbs_meallog_fat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_logs',
            field=models.ManyToManyField(related_name='meals', to='FitedSync.meallog'),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='calories',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='carbs',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='fat',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='protein',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
