# Generated by Django 5.1 on 2024-11-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0023_alter_meallog_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meallog',
            old_name='carbs',
            new_name='carbohydrates',
        ),
    ]
