# Generated by Django 5.1 on 2024-11-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0025_meallog_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='food',
            new_name='food_name',
        ),
    ]
