# Generated by Django 5.1 on 2024-11-23 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0026_rename_food_fooditem_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
