# Generated by Django 5.1 on 2024-11-24 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitedSync', '0027_alter_workoutlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustWorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('routine_name', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
